services:
  backend:
    build:
      context: ./backend
    ports:
      - "8899:8899"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    ports:
      - "8890:3000"
    stdin_open: true
    tty: true